services:
  frontend:
    image: congtoan0101/vite-app:latest
    ports:
      - "5173:80"
    restart: unless-stopped

  backend:
    image: congtoan0101/springboot-app:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped