CREATE TYPE IF NOT EXISTS user_role AS ENUM ('TRAVELER', 'ADMIN', 'BUDDY');
CREATE TYPE IF NOT EXISTS booking_status AS ENUM ('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'REJECTED');
CREATE TYPE IF NOT EXISTS meetup_status AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED');
CREATE TYPE IF NOT EXISTS payment_status AS ENUM ('PENDING', 'HELD', 'RELEASED', 'REFUNDED', 'FAILED');
CREATE TYPE IF NOT EXISTS payment_type AS ENUM ('DEPOSIT', 'FULL_PAYMENT', 'REFUND');
CREATE TYPE IF NOT EXISTS payout_status AS ENUM ('PENDING', 'PAID', 'REJECTED');
CREATE TYPE IF NOT EXISTS transaction_type AS ENUM ('INCOME', 'PAYOUT');
CREATE TYPE IF NOT EXISTS verification_status AS ENUM (
    'PENDING',
    'PROCESSING',
    'AUTO_APPROVED',
    'MANUAL_REVIEW',
    'AUTO_REJECTED',
    'MANUAL_APPROVED',
    'MANUAL_REJECTED',
    'VERIFIED',
    'REJECTED'
);
