spring.application.name=backend


#Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.properties.hibernate.types.auto_register=true


#Hibernate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.statement_cache.size=0
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
#Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#
##Message_Lang
#spring.messages.basename=messages
#spring.messages.encoding=UTF-8
#app.language=vi



#Security
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
# JWT Configurations
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000
app.oauth2.redirect-uri-frontend=http://localhost:5173/oauth2/success
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#API Frontend
api.frontend=http://localhost:5173/

spring.datasource.hikari.data-source-properties.prepareThreshold=0
## Log chi ti\u1EBFt cho controller v\u00E0 l\u1ED7i web
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.web.servlet=DEBUG
#logging.level.org.springframework.http.converter.json=DEBUG

# Log  Hibernate (ORM)
#logging.level.org.hibernate=ERROR

# Log exception
#logging.level.root=INFO

#spring.jpa.properties.hibernate.generate_statistics=true
#logging.level.org.hibernate.stat=DEBUG
